# scripts/02_process/covid_outlier_check.R
# Documents the COVID outlier decision:
# Option A: correct outliers (smooth the shock)
# Option B: keep raw (model captures the shock — our choice)
# Produces comparison plot and justification table

library(dplyr)
library(readr)
library(ggplot2)
library(yaml)
library(here)

cfg    <- yaml::read_yaml(here("config", "config.yaml"))
fig_dir <- here("outputs", "figures")
ms_dir  <- here("outputs", "manuscript")

df <- read_csv(here("data/processed/traditional_indicators.csv"),
               show_col_types=FALSE) |>
  mutate(date=as.Date(date))

# ── Identify COVID outliers ───────────────────────────────────────────────────
# Outlier = |igae_ldiff| > mean + 3*sd
mu  <- mean(df$igae_ldiff, na.rm=TRUE)
sig <- sd(df$igae_ldiff, na.rm=TRUE)
threshold <- 3 * sig

outliers <- df |>
  filter(!is.na(igae_ldiff)) |>
  mutate(
    is_outlier = abs(igae_ldiff - mu) > threshold,
    type       = ifelse(is_outlier, "Outlier (>3σ)", "Normal")
  )

cat("── Outlier summary ──────────────────────────────────────────────────\n")
cat(sprintf("Mean: %.4f, SD: %.4f, Threshold: ±%.4f\n", mu, sig, threshold))
cat(sprintf("Outliers identified: %d\n", sum(outliers$is_outlier, na.rm=TRUE)))
cat("Outlier dates:\n")
print(outliers |> filter(is_outlier) |> select(date, igae_ldiff))

# ── Option A: winsorise at ±3sd ───────────────────────────────────────────────
df_corrected <- df |>
  mutate(igae_ldiff_corrected = pmax(pmin(igae_ldiff, mu + threshold),
                                      mu - threshold))

# ── Plot: raw vs corrected ────────────────────────────────────────────────────
plot_df <- df_corrected |>
  filter(!is.na(igae_ldiff), date >= as.Date("2018-01-01")) |>
  select(date, `Raw (used in models)`=igae_ldiff,
         `Winsorised at ±3σ`=igae_ldiff_corrected) |>
  tidyr::pivot_longer(-date, names_to="series", values_to="value")

p <- ggplot(plot_df, aes(x=date, y=value, color=series, linetype=series)) +
  geom_line(linewidth=0.7) +
  geom_hline(yintercept=c(mu+threshold, mu-threshold),
             linetype="dotted", color="grey50", linewidth=0.4) +
  scale_color_manual(values=c("Raw (used in models)"="black",
                               "Winsorised at ±3σ"="#E07B54")) +
  scale_linetype_manual(values=c("Raw (used in models)"="solid",
                                  "Winsorised at ±3σ"="dashed")) +
  annotate("text", x=as.Date("2020-08-01"), y=mu+threshold+0.01,
           label="+3σ threshold", size=3, color="grey50") +
  labs(
    title    = "IGAE Monthly Growth: Raw vs. Winsorised",
    subtitle = "Dotted lines show ±3σ outlier thresholds",
    x=NULL, y="Log-difference", color=NULL, linetype=NULL
  ) +
  theme_minimal(base_size=11) +
  theme(legend.position="bottom", panel.grid.minor=element_blank())

ggsave(file.path(fig_dir, "covid_outlier_check.png"), p,
       width=10, height=5, dpi=300)
cat("\nSaved -> outputs/figures/covid_outlier_check.png\n")

# ── Write justification note for manuscript ───────────────────────────────────
note <- c(
  "% covid_outlier_note.tex",
  "% Auto-generated by covid_outlier_check.R",
  "",
  "\\paragraph{COVID-19 outlier treatment.}",
  sprintf("The March--May 2020 COVID-19 shock produces %d observations with",
          sum(outliers$is_outlier, na.rm=TRUE)),
  "|growth rate| $> 3\\sigma$ (threshold: $\\pm$",
  sprintf("%.3f$). We retain the raw series rather than winsorising for three reasons.", threshold),
  "First, the COVID shock is a genuine economic event, not a measurement error.",
  "Second, our pseudo out-of-sample evaluation is designed to test how models",
  "perform in real time, including during crises --- smoothing the target would",
  "inflate apparent model accuracy during the most policy-relevant period.",
  "Third, Figure~\\ref{fig:rolling_rmse} shows that LASSO with alternative data",
  "achieves substantially lower RMSE precisely during the shock period,",
  "demonstrating that the alternative data adds value when it is most needed."
)
writeLines(note, file.path(ms_dir, "covid_outlier_note.tex"))
cat("Saved -> outputs/manuscript/covid_outlier_note.tex\n")
